# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'The name of the organization', max_length=100)),
                ('website', models.URLField(help_text=b"URL of the ogranization's website", max_length=250)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[(b'women', b'Women'), (b'racial_minorities', b'Racial Minorities'), (b'religious_minorities', b'Religious Minorities'), (b'immigrants', b'Immigrants'), (b'youths', b'Youths'), (b'disabled', b'Disabled'), (b'environment', b'Environment'), (b'civil_rights', b'Civil Rights'), (b'sexual_abuse', b'Sexual Abuse'), (b'lgbt', b'LGBT'), (b'reproduction', b'Reproduction'), (b'homeless', b'Homeless'), (b'guns', b'Guns')], max_length=141)),
                ('acronym', models.CharField(blank=True, help_text=b"Acronym of the organization if it's widely used", max_length=25)),
                ('donate_url', models.URLField(blank=True, help_text=b"URL to org's 'donate' page")),
                ('involvement_url', models.URLField(blank=True, help_text=b"URL to org's 'take action' or 'get involved' or 'volunteer' page")),
                ('description', models.TextField(blank=True, help_text=b'Mission statement of the org')),
                ('facebook_url', models.URLField(blank=True, help_text=b"URL of org's Facebook group")),
                ('twitter_handle', models.CharField(blank=True, help_text=b'Twitter handle of the organization, including @ sign', max_length=50)),
            ],
        ),
    ]
