# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 01:59
from __future__ import unicode_literals

import csv

from django.db import migrations


def import_org_data(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')

    with open('organizations/fixtures/national_orgs.csv','r') as infile:
        inreader = csv.reader(infile)
        inreader.next()  # skip headers
        for row in inreader:
            name = row[0]
            acronym = row[1]
            website = row[2]
            description = row[3]
            donate_url = row[4]
            involvement_url = row[5]
            facebook_url = row[6]
            twitter_handle = row[7]
            categories = row[8].replace(' ',',')

            print categories

            Organization.objects.create(
                name=name,
                acronym=acronym,
                website=website,
                description=description,
                donate_url=donate_url,
                involvement_url=involvement_url,
                facebook_url=facebook_url,
                twitter_handle=twitter_handle,
                categories=categories
            )


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_org_data,reverse),
    ]
