# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this RSS feed (ex. BBC World News)', max_length=100)),
                ('url', models.URLField(help_text='URL of the RSS feed', max_length=250)),
                ('favicon', models.ImageField(upload_to='feed/favicons/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the article', max_length=250)),
                ('url', models.URLField(help_text='URL of the article', max_length=250)),
                ('pub_date', models.DateTimeField(help_text='Datetime of article pub date in EST')),
                ('summary', models.TextField(help_text='Summary of the article')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Feed')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
