# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='favicon',
            field=models.CharField(help_text="File name of favicon we're using; located in static/img/feed/favicons/", max_length=50),
        ),
    ]
